// AUTO-GENERATED by wheelhouse/contract/generate.py
// DO NOT EDIT - regenerate with: python -m wheelhouse.contract.generate

/** Task lifecycle status. */
export type TaskStatus = "pending" | "assigned" | "in_progress" | "checking" | "blocked" | "completed" | "failed";

/** Project lifecycle status. */
export type ProjectStatus = "draft" | "planning" | "ready" | "running" | "completed" | "failed" | "cancelled";

/** Sprint lifecycle status. */
export type SprintStatus = "draft" | "ready" | "running" | "blocked" | "completed" | "failed" | "cancelled";

/** Per-task execution strategy. */
export type ExecutionPattern = "sequential" | "tournament" | "cascade";

/** Task distribution strategy. */
export type DistributionMode = "single" | "swarm";

/** Model tier for cascade execution. */
export type ModelTier = "haiku" | "sonnet" | "opus";

/** Planning session state. */
export type SessionState = "initializing" | "active" | "idle" | "expired";

/** Planning conversation status. */
export type PlanningStatus = "active" | "approved" | "rejected" | "cancelled";

/** Blocker lifecycle status. */
export type BlockerStatus = "open" | "resolved" | "dismissed";

/** How the blocker was created. */
export type BlockerType = "planned" | "discovered";

/** Type of human input required to resolve. */
export type BlockerInputType = "secret" | "text" | "choice";

/** How much planning rigor to apply. */
export type PlanningRigor = "delegate" | "review" | "collaborate";

/** How atomic tasks should be in decomposition. */
export type TaskGranularity = "coarse" | "standard" | "fine" | "atomic" | "custom";

/** A success criterion for a task. */
export interface Criterion {
  id?: string;
  description: string;
  check_type?: "test" | "lint" | "manual";
  status?: "pending" | "passed" | "failed";
  result_message?: string;
}

/** A task to be implemented by agents. */
export interface Task {
  id?: string;
  title: string;
  description?: string;
  status?: TaskStatus;
  criteria?: Criterion[];
  assignee?: string;
  branch?: string;
  pr_url?: string;
  attempt?: number;
  max_attempts?: number;
  created_at?: string;
  updated_at?: string;
}

/** Multi-sprint initiative. */
export interface Project {
  id: string;
  name: string;
  description?: string;
  repo_url: string;
  default_branch?: string;
  status?: ProjectStatus;
  metadata?: Record<string, unknown>;
  created_at?: string;
  started_at?: string;
  completed_at?: string;
}

/** Focused work period within a project. */
export interface Sprint {
  id: string;
  project_id: string;
  name: string;
  description?: string;
  order_index?: number;
  status?: SprintStatus;
  metadata?: Record<string, unknown>;
  created_at?: string;
  started_at?: string;
  completed_at?: string;
}

/** A recommended task within a sprint. */
export interface TaskRecommendation {
  title: string;
  description: string;
  complexity?: "small" | "medium" | "large";
  execution_pattern?: ExecutionPattern;
  distribution_mode?: DistributionMode;
  pattern_config?: Record<string, unknown>;
  estimated_minutes?: number;
}

/** A recommended sprint within a project. */
export interface SprintRecommendation {
  name: string;
  description?: string;
  tasks?: TaskRecommendation[];
}

/** A recommended project decomposition from planning. */
export interface ProjectRecommendation {
  name: string;
  description?: string;
  repo_url?: string;
  sprints?: SprintRecommendation[];
}

/** Configuration for tournament pattern. */
export interface TournamentConfig {
  agent_count?: number;
  timeout_per_agent?: number;
  selection_criteria?: string[];
  require_all_complete?: boolean;
  first_wins?: boolean;
}

/** Configuration for cascade pattern. */
export interface CascadeConfig {
  tiers?: ModelTier[];
  success_criteria?: "tests_pass" | "builds" | "criteria_met";
  max_escalations?: number;
}

/** Configuration for swarm distribution. */
export interface SwarmConfig {
  num_workers?: number;
  task_timeout?: number;
  per_task_pattern?: ExecutionPattern;
  per_task_config?: TournamentConfig | CascadeConfig;
}

/** Unified execution configuration. */
export interface ExecutionConfig {
  distribution_mode?: DistributionMode;
  execution_pattern?: ExecutionPattern;
  tournament_config?: TournamentConfig;
  cascade_config?: CascadeConfig;
  swarm_config?: SwarmConfig;
  forced?: boolean;
}

/** Structured action taken during planning. */
export interface ActionTaken {
  type: "project_created" | "sprint_created" | "task_created" | "task_updated" | "task_deleted";
  id: string;
  name: string;
  url: string;
  parent_id?: string;
  metadata?: Record<string, unknown>;
}

/** Subset of PlanningSession exposed to the dashboard. */
export interface PlanningSessionSummary {
  session_id: string;
  conversation_id: string;
  state: SessionState;
  message_count?: number;
}

/** Shape returned by GET /projects (each item in the projects array). */
export interface ProjectListItem {
  id: string;
  name: string;
  description: string;
  status: ProjectStatus;
  client_id?: string;
  repo_id?: string;
  notion_id?: string;
  planning_rigor?: string;
  task_granularity?: string;
  created_at?: string;
  client_name?: string;
  repo_name?: string;
  sprint_count?: number;
  sprints_completed?: number;
  task_count?: number;
  tasks_completed?: number;
}

/** Shape returned by GET /projects/{id} (the project object). */
export interface ProjectDetail {
  id: string;
  name: string;
  description: string;
  status: ProjectStatus;
  client_id?: string;
  repo_id?: string;
  notion_id?: string;
  planning_rigor?: string;
  task_granularity?: string;
  granularity_instructions?: string;
  repo_url?: string;
  default_branch?: string;
  created_at?: string;
  client_name?: string;
  repo_name?: string;
  github_org?: string;
  github_repo?: string;
  sprint_count?: number;
  sprints_completed?: number;
  task_count?: number;
  tasks_completed?: number;
  sprints?: SprintListItem[];
}

/** Shape returned within project detail (sprint with nested tasks). */
export interface SprintListItem {
  id: string;
  project_id?: string;
  name: string;
  description: string;
  order_index: number;
  status: SprintStatus;
  pattern?: ExecutionPattern;
  distribution?: DistributionMode;
  pattern_config?: Record<string, unknown>;
  started_at?: string;
  completed_at?: string;
  tasks?: TaskListItem[];
}

/** Shape returned within sprint detail or task listings. */
export interface TaskListItem {
  id: string;
  title: string;
  description: string;
  status: TaskStatus;
  sprint_id?: string;
  execution_pattern?: ExecutionPattern;
  distribution_mode?: DistributionMode;
  blocker_count?: number;
  has_open_blockers?: boolean;
}

/** Shape for POST /execute request body. */
export interface ExecuteRequest {
  level: string;
  id: string;
  action: string;
  pattern?: ExecutionPattern;
  distribution?: DistributionMode;
  workers?: number;
  pattern_config?: Record<string, unknown>;
}

/** Shape for POST /execute response. */
export interface ExecuteResponse {
  success: boolean;
  message: string;
  execution_id?: string;
  execution_ids?: string[];
  status?: string;
  pattern?: string;
  distribution?: string;
  started_at?: string;
  current_sprint?: string;
  tasks_started?: number;
}

/** Shape for POST /planning/chat request body. */
export interface PlanningChatRequest {
  message: string;
  repoUrl?: string;
  projectId?: string;
  conversationId?: string;
  history?: Record<string, unknown>[];
}

/** Shape for POST /planning/approve request body. */
export interface PlanningApproveRequest {
  conversationId: string;
  modifications?: Record<string, unknown>;
}

/** Shape for POST /planning/approve response. */
export interface PlanningApproveResponse {
  success: boolean;
  project_id?: string;
  sprint_ids?: string[];
  task_ids?: string[];
  blocker_ids?: string[];
  blockers_created?: number;
  actions_taken?: ActionTaken[];
  message?: string;
}

/** Union of all possible SSE event shapes streamed from /planning/chat. */
export interface PlanningSSEEvent {
  conversation_id?: string;
  phase?: string;
  message?: string;
  icon?: string;
  content?: string;
  actions_taken?: ActionTaken[];
  done?: boolean;
  error?: string;
  elapsed?: number;
}

/** Response shape for POST /projects. */
export interface CreateProjectResponse {
  success: boolean;
  project_id: string;
  message: string;
}

/** Response shape for POST /sprints. */
export interface CreateSprintResponse {
  success: boolean;
  sprint_id: string;
  message: string;
}

/** Response shape for POST /tasks. */
export interface CreateTaskResponse {
  success: boolean;
  task_id: string;
  message: string;
}

/** Response shape for DELETE endpoints. */
export interface DeleteResponse {
  success: boolean;
  message: string;
  cascade_deleted?: Record<string, number>;
}

/** Response shape for agent execution summaries. */
export interface AgentSummaryResponse {
  id: string;
  agent_id: string;
  agent_role: string;
  task_id: string;
  sprint_id?: string;
  started_at: string;
  completed_at: string;
  success: boolean;
  summary: string;
  files_modified?: string[];
  key_decisions?: string[];
  issues_encountered?: string[];
  error?: string;
  metadata?: Record<string, unknown>;
  created_at: string;
}

/** Task summary within execution status response. */
export interface TaskStatusDetail {
  id: string;
  title: string;
  status: TaskStatus;
  progress?: number;
  pattern?: string;
  error?: string;
  pr_url?: string;
  blocker_count?: number;
}

/** Sprint summary within execution status response. */
export interface SprintStatusDetail {
  id: string;
  name: string;
  status: SprintStatus;
  pattern?: string;
}

/** Shape for GET /execute/status/{entity_id} response. */
export interface ExecutionStatusResponse {
  success: boolean;
  type: string;
  id: string;
  status: string;
  progress?: number;
  pattern?: string;
  distribution?: string;
  error?: string;
  started_at?: string;
  completed_at?: string;
  pr_url?: string;
  pr_number?: number;
  branch?: string;
  total_tasks?: number;
  completed_tasks?: number;
  failed_tasks?: number;
  finished_tasks?: number;
  running_tasks?: number;
  blocked_tasks?: number;
  open_blockers?: number;
  tasks?: TaskStatusDetail[];
  sprints?: SprintStatusDetail[];
}

/** Shape returned by GET /clients (each item in the clients array). */
export interface ClientListItem {
  id: string;
  name: string;
  status: string;
  client_type: string;
  notion_id?: string;
  contact_email?: string;
  created_at?: string;
}

/** Shape returned by GET /clients/{id}. */
export interface ClientDetail {
  id: string;
  name: string;
  status: string;
  client_type: string;
  notion_id?: string;
  contact_email?: string;
  contact_phone?: string;
  metadata?: Record<string, unknown>;
  created_at?: string;
  updated_at?: string;
}

/** Response shape for POST /clients. */
export interface CreateClientResponse {
  success: boolean;
  client_id: string;
  message: string;
}

/** Shape returned by GET /repos (each item in the repos array). */
export interface RepoListItem {
  id: string;
  client_id?: string;
  name: string;
  github_org: string;
  github_repo: string;
  default_branch?: string;
  repo_url?: string;
  created_at?: string;
}

/** Shape returned by GET /repos/{id}. */
export interface RepoDetail {
  id: string;
  client_id?: string;
  name: string;
  github_org: string;
  github_repo: string;
  default_branch?: string;
  repo_url?: string;
  description?: string;
  metadata?: Record<string, unknown>;
  created_at?: string;
  updated_at?: string;
}

/** Response shape for POST /repos. */
export interface CreateRepoResponse {
  success: boolean;
  repo_id: string;
  message: string;
}

/** Shape for a single Notion task row from Supabase cache. */
export interface NotionTaskResponse {
  id: string;
  notion_page_id: string;
  title: string;
  status: string;
  priority?: string;
  task_type?: string;
  client_name?: string;
  project_name?: string;
  due_date?: string;
  estimated_time?: number;
  wheelhouse_task_id?: string;
  notion_created_at?: string;
  notion_last_edited?: string;
  synced_at?: string;
  created_at?: string;
}

/** Shape for POST /notion/sync response. */
export interface NotionSyncResponse {
  synced: number;
  errors?: number;
  missing_marked: number;
  timestamp: string;
}

export interface ContextAttachmentResponse {
  id: string;
  client_id?: string;
  repo_id?: string;
  project_id?: string;
  sprint_id?: string;
  task_id?: string;
  type: string;
  title: string;
  description?: string;
  url?: string;
  notion_page_id?: string;
  mime_type?: string;
  file_size_bytes?: number;
  ai_context_summary?: string;
  storage_path?: string;
  created_at?: string;
  updated_at?: string;
}

export interface ProjectNotionLinkResponse {
  id: string;
  project_id: string;
  notion_page_id: string;
  notion_task_id?: string;
  role?: string;
  title?: string;
  url?: string;
  created_at?: string;
}

/** Schema describing what human input a blocker needs. */
export interface BlockerInputSchema {
  type: BlockerInputType;
  label: string;
  description?: string;
  options?: string[];
}

/** Shape returned by GET /blockers. */
export interface BlockerListItem {
  id: string;
  task_id?: string;
  sprint_id?: string;
  project_id?: string;
  title: string;
  description?: string;
  blocker_type: BlockerType;
  status: BlockerStatus;
  input_schema: BlockerInputSchema;
  resolution?: string;
  resolved_at?: string;
  source_error?: string;
  created_at?: string;
}

/** Shape for POST /blockers. */
export interface CreateBlockerRequest {
  task_id?: string;
  sprint_id?: string;
  project_id?: string;
  title: string;
  description?: string;
  blocker_type?: BlockerType;
  input_schema?: BlockerInputSchema;
}

/** Response shape for POST /blockers. */
export interface CreateBlockerResponse {
  success: boolean;
  blocker_id: string;
  message: string;
}

/** Shape for POST /blockers/{id}/resolve. */
export interface ResolveBlockerRequest {
  resolution: string;
  resolved_by?: string;
}

/** Response shape for POST /blockers/{id}/resolve. */
export interface ResolveBlockerResponse {
  success: boolean;
  blocker_id: string;
  task_id?: string;
  auto_resumed?: boolean;
  message: string;
}

/** Shape for POST /planning/decline. */
export interface PlanningDeclineRequest {
  conversationId: string;
  feedback: string;
}

/** Response for POST /planning/decline — triggers regeneration. */
export interface PlanningDeclineResponse {
  success: boolean;
  message: string;
  conversation_id: string;
  regeneration_started?: boolean;
}

/** Shape for POST /projects request body. */
export interface CreateProjectRequest {
  name: string;
  description?: string;
  repo_url?: string;
  client_id?: string;
  repo_id?: string;
  planning_rigor?: string;
  task_granularity?: string;
  granularity_instructions?: string;
}

/** Dashboard stats overview response. */
export interface StatsOverviewResponse {
  total_projects?: number;
  active_projects?: number;
  total_tasks?: number;
  tasks_completed?: number;
  tasks_in_progress?: number;
  tasks_blocked?: number;
  notion_tasks_to_delegate?: number;
}

