// AUTO-GENERATED by wheelhouse/contract/generate.py
// DO NOT EDIT - regenerate with: python -m wheelhouse.contract.generate

/** Task lifecycle status. */
export type TaskStatus = "pending" | "assigned" | "in_progress" | "checking" | "complete" | "failed";

/** Project lifecycle status. */
export type ProjectStatus = "draft" | "planning" | "ready" | "running" | "completed" | "failed" | "cancelled";

/** Sprint lifecycle status. */
export type SprintStatus = "draft" | "ready" | "running" | "completed" | "failed" | "cancelled";

/** Per-task execution strategy. */
export type ExecutionPattern = "sequential" | "tournament" | "ensemble" | "cascade";

/** Task distribution strategy. */
export type DistributionMode = "single" | "swarm";

/** Model tier for cascade execution. */
export type ModelTier = "haiku" | "sonnet" | "opus";

/** Planning session state. */
export type SessionState = "initializing" | "active" | "idle" | "expired";

/** Planning conversation status. */
export type PlanningStatus = "active" | "approved" | "rejected" | "cancelled";

/** A success criterion for a task. */
export interface Criterion {
  id?: string;
  description: string;
  check_type?: "test" | "lint" | "manual";
  status?: "pending" | "passed" | "failed";
  result_message?: string;
}

/** A task to be implemented by agents. */
export interface Task {
  id?: string;
  title: string;
  description?: string;
  status?: TaskStatus;
  criteria?: Criterion[];
  assignee?: string;
  branch?: string;
  pr_url?: string;
  attempt?: number;
  max_attempts?: number;
  created_at?: string;
  updated_at?: string;
}

/** Multi-sprint initiative. */
export interface Project {
  id: string;
  name: string;
  description?: string;
  repo_url: string;
  default_branch?: string;
  status?: ProjectStatus;
  metadata?: Record<string, unknown>;
  created_at?: string;
  started_at?: string;
  completed_at?: string;
}

/** Focused work period within a project. */
export interface Sprint {
  id: string;
  project_id: string;
  name: string;
  description?: string;
  order_index?: number;
  status?: SprintStatus;
  metadata?: Record<string, unknown>;
  created_at?: string;
  started_at?: string;
  completed_at?: string;
}

/** A recommended task within a sprint. */
export interface TaskRecommendation {
  title: string;
  description: string;
  complexity?: "small" | "medium" | "large";
  execution_pattern?: ExecutionPattern;
  distribution_mode?: DistributionMode;
  pattern_config?: Record<string, unknown>;
  estimated_minutes?: number;
}

/** A recommended sprint within a project. */
export interface SprintRecommendation {
  name: string;
  description?: string;
  tasks?: TaskRecommendation[];
}

/** A recommended project decomposition from planning. */
export interface ProjectRecommendation {
  name: string;
  description?: string;
  repo_url?: string;
  sprints?: SprintRecommendation[];
}

/** Configuration for tournament pattern. */
export interface TournamentConfig {
  agent_count?: number;
  timeout_per_agent?: number;
  selection_criteria?: string[];
  require_all_complete?: boolean;
  first_wins?: boolean;
}

/** Configuration for ensemble pattern. */
export interface EnsembleConfig {
  decomposition_strategy?: "file_based" | "functional" | "layer_based";
  max_subtasks?: number;
  merge_strategy?: "sequential" | "parallel" | "conflict_resolution";
}

/** Configuration for cascade pattern. */
export interface CascadeConfig {
  tiers?: ModelTier[];
  success_criteria?: "tests_pass" | "builds" | "criteria_met";
  max_escalations?: number;
}

/** Configuration for swarm distribution. */
export interface SwarmConfig {
  num_workers?: number;
  task_timeout?: number;
  per_task_pattern?: ExecutionPattern;
  per_task_config?: TournamentConfig | EnsembleConfig | CascadeConfig;
}

/** Unified execution configuration. */
export interface ExecutionConfig {
  distribution_mode?: DistributionMode;
  execution_pattern?: ExecutionPattern;
  tournament_config?: TournamentConfig;
  ensemble_config?: EnsembleConfig;
  cascade_config?: CascadeConfig;
  swarm_config?: SwarmConfig;
  forced?: boolean;
}

/** Structured action taken during planning. */
export interface ActionTaken {
  type: "project_created" | "sprint_created" | "task_created" | "task_updated" | "task_deleted";
  id: string;
  name: string;
  url: string;
  parent_id?: string;
  metadata?: Record<string, unknown>;
}

/** Subset of PlanningSession exposed to the dashboard. */
export interface PlanningSessionSummary {
  session_id: string;
  conversation_id: string;
  state: SessionState;
  message_count?: number;
}

/** Shape returned by GET /projects (each item in the projects array). */
export interface ProjectListItem {
  id: string;
  name: string;
  description: string;
  status: ProjectStatus;
  created_at?: string;
}

/** Shape returned by GET /projects/{id} (the project object). */
export interface ProjectDetail {
  id: string;
  name: string;
  description: string;
  status: ProjectStatus;
  repo_url?: string;
  default_branch?: string;
  created_at?: string;
  sprints?: SprintListItem[];
}

/** Shape returned within project detail (sprint with nested tasks). */
export interface SprintListItem {
  id: string;
  project_id?: string;
  name: string;
  description: string;
  order_index: number;
  status: SprintStatus;
  tasks?: TaskListItem[];
}

/** Shape returned within sprint detail or task listings. */
export interface TaskListItem {
  id: string;
  title: string;
  description: string;
  status: TaskStatus;
  sprint_id?: string;
  execution_pattern?: ExecutionPattern;
  distribution_mode?: DistributionMode;
}

/** Shape for POST /execute request body. */
export interface ExecuteRequest {
  level: string;
  id: string;
  action: string;
  pattern?: ExecutionPattern;
  distribution?: DistributionMode;
  workers?: number;
  pattern_config?: Record<string, unknown>;
}

/** Shape for POST /execute response. */
export interface ExecuteResponse {
  success: boolean;
  message: string;
  execution_id?: string;
}

/** Shape for POST /planning/chat request body. */
export interface PlanningChatRequest {
  message: string;
  repoUrl?: string;
  projectId?: string;
  conversationId?: string;
  history?: Record<string, unknown>[];
}

/** Shape for POST /planning/approve request body. */
export interface PlanningApproveRequest {
  conversationId: string;
  modifications?: Record<string, unknown>;
}

/** Shape for POST /planning/approve response. */
export interface PlanningApproveResponse {
  success: boolean;
  project_id?: string;
  sprint_ids?: string[];
  task_ids?: string[];
  actions_taken?: ActionTaken[];
  message?: string;
}

/** Union of all possible SSE event shapes streamed from /planning/chat. */
export interface PlanningSSEEvent {
  conversation_id?: string;
  phase?: string;
  message?: string;
  icon?: string;
  content?: string;
  actions_taken?: ActionTaken[];
  done?: boolean;
  error?: string;
  elapsed?: number;
}

/** Response shape for POST /projects. */
export interface CreateProjectResponse {
  success: boolean;
  project_id: string;
  message: string;
}

/** Response shape for POST /sprints. */
export interface CreateSprintResponse {
  success: boolean;
  sprint_id: string;
  message: string;
}

/** Response shape for POST /tasks. */
export interface CreateTaskResponse {
  success: boolean;
  task_id: string;
  message: string;
}

/** Response shape for DELETE endpoints. */
export interface DeleteResponse {
  success: boolean;
  message: string;
  cascade_deleted?: Record<string, number>;
}

